// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1mZ9_Nr2H8_yAOfb2gYPBDGLlj4l6ppU',
    appId: '1:427601663804:web:25d0b66333b358c4147039',
    messagingSenderId: '427601663804',
    projectId: 'notinsta-24f17',
    authDomain: 'notinsta-24f17.firebaseapp.com',
    storageBucket: 'notinsta-24f17.firebasestorage.app',
    measurementId: 'G-3BQYM64TZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Q2XEjQiYqjHx6j0e0Kgk_o0wiHZMMro',
    appId: '1:427601663804:android:a954752a5a616ecf147039',
    messagingSenderId: '427601663804',
    projectId: 'notinsta-24f17',
    storageBucket: 'notinsta-24f17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyYQydp09U_l8dgoDannHqn2-XoqPqTI',
    appId: '1:427601663804:ios:94fa8cc9a1c1896e147039',
    messagingSenderId: '427601663804',
    projectId: 'notinsta-24f17',
    storageBucket: 'notinsta-24f17.firebasestorage.app',
    iosBundleId: 'com.notmeta.notInsta',
  );
}
